env:
  es2021: true
  mocha: true
  node: true

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - prettier

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: "latest"
  sourceType: module

plugins:
  - "@typescript-eslint"

rules:
  "@typescript-eslint/explicit-function-return-type": warn
  "@typescript-eslint/explicit-module-boundary-types": warn
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
  "@typescript-eslint/no-explicit-any": warn
  camelcase: warn
  no-console: warn
