/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IZLETHWrapper } from "./IZLETHWrapper";
export type { ZamaLinkCampaign } from "./ZamaLinkCampaign";
