/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ZamaLinkCampaignInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeCampaigns"
      | "allCampaigns"
      | "allowOrganizerDecrypt"
      | "campaignDonations"
      | "campaigns"
      | "claimFunds"
      | "completeCampaign"
      | "confidentialProtocolId"
      | "createCampaign"
      | "donate"
      | "donorCampaigns"
      | "getActiveCampaigns"
      | "getAllCampaigns"
      | "getCampaignInfo"
      | "getCampaignsByOrganizer"
      | "getEncryptedTotals"
      | "getRecentDonations"
      | "hasDonatedTo"
      | "organizerCampaigns"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "transferOwnership"
      | "unpause"
      | "updateZLETHWrapper"
      | "zlethWrapper"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCompleted"
      | "CampaignCreated"
      | "FundsClaimedPrivate"
      | "OwnershipTransferred"
      | "Paused"
      | "PrivateDonationMade"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeCampaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allCampaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allowOrganizerDecrypt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignDonations",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimFunds",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "completeCampaign",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [
      BytesLike,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "donorCampaigns",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCampaigns",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCampaignsByOrganizer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTotals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentDonations",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasDonatedTo",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "organizerCampaigns",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateZLETHWrapper",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "zlethWrapper",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "activeCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowOrganizerDecrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignDonations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimFunds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "donorCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCampaignsByOrganizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTotals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentDonations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasDonatedTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "organizerCampaigns",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateZLETHWrapper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zlethWrapper",
    data: BytesLike
  ): Result;
}

export namespace CampaignCompletedEvent {
  export type InputTuple = [campaignId: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [campaignId: string, timestamp: bigint];
  export interface OutputObject {
    campaignId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    organizer: AddressLike,
    title: string,
    targetAmount: BigNumberish,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    organizer: string,
    title: string,
    targetAmount: bigint,
    deadline: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    organizer: string;
    title: string;
    targetAmount: bigint;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsClaimedPrivateEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    organizer: AddressLike,
    requestId: BigNumberish
  ];
  export type OutputTuple = [
    campaignId: string,
    organizer: string,
    requestId: bigint
  ];
  export interface OutputObject {
    campaignId: string;
    organizer: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrivateDonationMadeEvent {
  export type InputTuple = [
    campaignId: BytesLike,
    donor: AddressLike,
    timestamp: BigNumberish,
    isAnonymous: boolean
  ];
  export type OutputTuple = [
    campaignId: string,
    donor: string,
    timestamp: bigint,
    isAnonymous: boolean
  ];
  export interface OutputObject {
    campaignId: string;
    donor: string;
    timestamp: bigint;
    isAnonymous: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZamaLinkCampaign extends BaseContract {
  connect(runner?: ContractRunner | null): ZamaLinkCampaign;
  waitForDeployment(): Promise<this>;

  interface: ZamaLinkCampaignInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeCampaigns: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  allCampaigns: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  allowOrganizerDecrypt: TypedContractMethod<
    [campaignId: BytesLike],
    [void],
    "nonpayable"
  >;

  campaignDonations: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        donor: string;
        campaignId: string;
        timestamp: bigint;
        isAnonymous: boolean;
      }
    ],
    "view"
  >;

  campaigns: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        id: string;
        organizer: string;
        title: string;
        description: string;
        imageUrl: string;
        targetAmount: bigint;
        deadline: bigint;
        totalZLETHDonations: string;
        donationCount: string;
        publicDonorCount: bigint;
        isActive: boolean;
        isCompleted: boolean;
        category: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  claimFunds: TypedContractMethod<
    [campaignId: BytesLike],
    [void],
    "nonpayable"
  >;

  completeCampaign: TypedContractMethod<
    [campaignId: BytesLike],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createCampaign: TypedContractMethod<
    [
      campaignId: BytesLike,
      title: string,
      description: string,
      imageUrl: string,
      targetAmount: BigNumberish,
      duration: BigNumberish,
      category: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  donate: TypedContractMethod<
    [campaignId: BytesLike, isAnonymous: boolean],
    [void],
    "payable"
  >;

  donorCampaigns: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getActiveCampaigns: TypedContractMethod<[], [string[]], "view">;

  getAllCampaigns: TypedContractMethod<[], [string[]], "view">;

  getCampaignInfo: TypedContractMethod<
    [campaignId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        organizer: string;
        title: string;
        description: string;
        imageUrl: string;
        targetAmount: bigint;
        deadline: bigint;
        publicDonorCount: bigint;
        isActive: boolean;
        category: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getCampaignsByOrganizer: TypedContractMethod<
    [organizer: AddressLike],
    [string[]],
    "view"
  >;

  getEncryptedTotals: TypedContractMethod<
    [campaignId: BytesLike],
    [[string, string] & { totalZLETH: string; donationCount: string }],
    "view"
  >;

  getRecentDonations: TypedContractMethod<
    [campaignId: BytesLike, limit: BigNumberish],
    [
      [string[], bigint[], boolean[]] & {
        donors: string[];
        timestamps: bigint[];
        isAnonymous: boolean[];
      }
    ],
    "view"
  >;

  hasDonatedTo: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  organizerCampaigns: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateZLETHWrapper: TypedContractMethod<
    [newWrapper: AddressLike],
    [void],
    "view"
  >;

  zlethWrapper: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeCampaigns"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allCampaigns"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "allowOrganizerDecrypt"
  ): TypedContractMethod<[campaignId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "campaignDonations"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        donor: string;
        campaignId: string;
        timestamp: bigint;
        isAnonymous: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint
      ] & {
        id: string;
        organizer: string;
        title: string;
        description: string;
        imageUrl: string;
        targetAmount: bigint;
        deadline: bigint;
        totalZLETHDonations: string;
        donationCount: string;
        publicDonorCount: bigint;
        isActive: boolean;
        isCompleted: boolean;
        category: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimFunds"
  ): TypedContractMethod<[campaignId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeCampaign"
  ): TypedContractMethod<[campaignId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      campaignId: BytesLike,
      title: string,
      description: string,
      imageUrl: string,
      targetAmount: BigNumberish,
      duration: BigNumberish,
      category: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<
    [campaignId: BytesLike, isAnonymous: boolean],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "donorCampaigns"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveCampaigns"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllCampaigns"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getCampaignInfo"
  ): TypedContractMethod<
    [campaignId: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint
      ] & {
        organizer: string;
        title: string;
        description: string;
        imageUrl: string;
        targetAmount: bigint;
        deadline: bigint;
        publicDonorCount: bigint;
        isActive: boolean;
        category: bigint;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCampaignsByOrganizer"
  ): TypedContractMethod<[organizer: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getEncryptedTotals"
  ): TypedContractMethod<
    [campaignId: BytesLike],
    [[string, string] & { totalZLETH: string; donationCount: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentDonations"
  ): TypedContractMethod<
    [campaignId: BytesLike, limit: BigNumberish],
    [
      [string[], bigint[], boolean[]] & {
        donors: string[];
        timestamps: bigint[];
        isAnonymous: boolean[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasDonatedTo"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "organizerCampaigns"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateZLETHWrapper"
  ): TypedContractMethod<[newWrapper: AddressLike], [void], "view">;
  getFunction(
    nameOrSignature: "zlethWrapper"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CampaignCompleted"
  ): TypedContractEvent<
    CampaignCompletedEvent.InputTuple,
    CampaignCompletedEvent.OutputTuple,
    CampaignCompletedEvent.OutputObject
  >;
  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsClaimedPrivate"
  ): TypedContractEvent<
    FundsClaimedPrivateEvent.InputTuple,
    FundsClaimedPrivateEvent.OutputTuple,
    FundsClaimedPrivateEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PrivateDonationMade"
  ): TypedContractEvent<
    PrivateDonationMadeEvent.InputTuple,
    PrivateDonationMadeEvent.OutputTuple,
    PrivateDonationMadeEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CampaignCompleted(bytes32,uint256)": TypedContractEvent<
      CampaignCompletedEvent.InputTuple,
      CampaignCompletedEvent.OutputTuple,
      CampaignCompletedEvent.OutputObject
    >;
    CampaignCompleted: TypedContractEvent<
      CampaignCompletedEvent.InputTuple,
      CampaignCompletedEvent.OutputTuple,
      CampaignCompletedEvent.OutputObject
    >;

    "CampaignCreated(bytes32,address,string,uint256,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "FundsClaimedPrivate(bytes32,address,uint256)": TypedContractEvent<
      FundsClaimedPrivateEvent.InputTuple,
      FundsClaimedPrivateEvent.OutputTuple,
      FundsClaimedPrivateEvent.OutputObject
    >;
    FundsClaimedPrivate: TypedContractEvent<
      FundsClaimedPrivateEvent.InputTuple,
      FundsClaimedPrivateEvent.OutputTuple,
      FundsClaimedPrivateEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PrivateDonationMade(bytes32,address,uint256,bool)": TypedContractEvent<
      PrivateDonationMadeEvent.InputTuple,
      PrivateDonationMadeEvent.OutputTuple,
      PrivateDonationMadeEvent.OutputObject
    >;
    PrivateDonationMade: TypedContractEvent<
      PrivateDonationMadeEvent.InputTuple,
      PrivateDonationMadeEvent.OutputTuple,
      PrivateDonationMadeEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
