/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AcademicEvaluation {
  export type PaperStruct = {
    id: BigNumberish;
    title: string;
    authors: string;
    ipfsHash: string;
    submitter: AddressLike;
    submissionDate: BigNumberish;
    isActive: boolean;
    evaluationCount: BigNumberish;
  };

  export type PaperStructOutput = [
    id: bigint,
    title: string,
    authors: string,
    ipfsHash: string,
    submitter: string,
    submissionDate: bigint,
    isActive: boolean,
    evaluationCount: bigint
  ] & {
    id: bigint;
    title: string;
    authors: string;
    ipfsHash: string;
    submitter: string;
    submissionDate: bigint;
    isActive: boolean;
    evaluationCount: bigint;
  };
}

export interface AcademicEvaluationInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeReviewers"
      | "confidentialProtocolId"
      | "deactivatePaper"
      | "emergencyPause"
      | "evaluationCount"
      | "evaluations"
      | "getActiveReviewers"
      | "getEncryptedRecommendation"
      | "getEncryptedScores"
      | "getEvaluationCount"
      | "getEvaluationInfo"
      | "getPaper"
      | "getPaperCount"
      | "getPaperEvaluations"
      | "getReviewerEvaluations"
      | "owner"
      | "paperCount"
      | "paperEvaluations"
      | "papers"
      | "reactivatePaper"
      | "renounceOwnership"
      | "reviewerEvaluations"
      | "submitEvaluation"
      | "submitPaper"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EvaluationRevealed"
      | "EvaluationSubmitted"
      | "OwnershipTransferred"
      | "PaperSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeReviewers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivatePaper",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evaluationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evaluations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveReviewers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedRecommendation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedScores",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvaluationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEvaluationInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaper",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaperCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPaperEvaluations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReviewerEvaluations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paperCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "paperEvaluations",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "papers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reactivatePaper",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reviewerEvaluations",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvaluation",
    values: [
      BigNumberish,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPaper",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeReviewers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivatePaper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveReviewers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedRecommendation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvaluationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvaluationInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPaper", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPaperCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaperEvaluations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReviewerEvaluations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paperCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paperEvaluations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "papers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactivatePaper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reviewerEvaluations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvaluation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitPaper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace EvaluationRevealedEvent {
  export type InputTuple = [
    evaluationId: BigNumberish,
    paperId: BigNumberish,
    recommendation: boolean,
    overallScore: BigNumberish
  ];
  export type OutputTuple = [
    evaluationId: bigint,
    paperId: bigint,
    recommendation: boolean,
    overallScore: bigint
  ];
  export interface OutputObject {
    evaluationId: bigint;
    paperId: bigint;
    recommendation: boolean;
    overallScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvaluationSubmittedEvent {
  export type InputTuple = [
    evaluationId: BigNumberish,
    paperId: BigNumberish,
    reviewer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    evaluationId: bigint,
    paperId: bigint,
    reviewer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    evaluationId: bigint;
    paperId: bigint;
    reviewer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaperSubmittedEvent {
  export type InputTuple = [
    paperId: BigNumberish,
    title: string,
    submitter: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    paperId: bigint,
    title: string,
    submitter: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    paperId: bigint;
    title: string;
    submitter: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AcademicEvaluation extends BaseContract {
  connect(runner?: ContractRunner | null): AcademicEvaluation;
  waitForDeployment(): Promise<this>;

  interface: AcademicEvaluationInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeReviewers: TypedContractMethod<[], [bigint], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  deactivatePaper: TypedContractMethod<
    [paperId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  evaluationCount: TypedContractMethod<[], [bigint], "view">;

  evaluations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        paperId: bigint;
        reviewer: string;
        recommendation: string;
        originality: string;
        quality: string;
        clarity: string;
        significance: string;
        comments: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getActiveReviewers: TypedContractMethod<[], [bigint], "view">;

  getEncryptedRecommendation: TypedContractMethod<
    [evaluationId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedScores: TypedContractMethod<
    [evaluationId: BigNumberish],
    [[string, string, string, string]],
    "view"
  >;

  getEvaluationCount: TypedContractMethod<[], [bigint], "view">;

  getEvaluationInfo: TypedContractMethod<
    [evaluationId: BigNumberish],
    [[bigint, string, string, bigint]],
    "view"
  >;

  getPaper: TypedContractMethod<
    [paperId: BigNumberish],
    [AcademicEvaluation.PaperStructOutput],
    "view"
  >;

  getPaperCount: TypedContractMethod<[], [bigint], "view">;

  getPaperEvaluations: TypedContractMethod<
    [paperId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getReviewerEvaluations: TypedContractMethod<
    [reviewer: AddressLike],
    [bigint[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paperCount: TypedContractMethod<[], [bigint], "view">;

  paperEvaluations: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  papers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean, bigint] & {
        id: bigint;
        title: string;
        authors: string;
        ipfsHash: string;
        submitter: string;
        submissionDate: bigint;
        isActive: boolean;
        evaluationCount: bigint;
      }
    ],
    "view"
  >;

  reactivatePaper: TypedContractMethod<
    [paperId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reviewerEvaluations: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  submitEvaluation: TypedContractMethod<
    [
      paperId: BigNumberish,
      _recommendation: boolean,
      _originality: BigNumberish,
      _quality: BigNumberish,
      _clarity: BigNumberish,
      _significance: BigNumberish,
      comments: string
    ],
    [void],
    "nonpayable"
  >;

  submitPaper: TypedContractMethod<
    [title: string, authors: string, ipfsHash: string],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeReviewers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivatePaper"
  ): TypedContractMethod<[paperId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "evaluationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "evaluations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        string,
        string,
        bigint
      ] & {
        paperId: bigint;
        reviewer: string;
        recommendation: string;
        originality: string;
        quality: string;
        clarity: string;
        significance: string;
        comments: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveReviewers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedRecommendation"
  ): TypedContractMethod<[evaluationId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedScores"
  ): TypedContractMethod<
    [evaluationId: BigNumberish],
    [[string, string, string, string]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvaluationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEvaluationInfo"
  ): TypedContractMethod<
    [evaluationId: BigNumberish],
    [[bigint, string, string, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaper"
  ): TypedContractMethod<
    [paperId: BigNumberish],
    [AcademicEvaluation.PaperStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaperCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPaperEvaluations"
  ): TypedContractMethod<[paperId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getReviewerEvaluations"
  ): TypedContractMethod<[reviewer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paperCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "paperEvaluations"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "papers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, boolean, bigint] & {
        id: bigint;
        title: string;
        authors: string;
        ipfsHash: string;
        submitter: string;
        submissionDate: bigint;
        isActive: boolean;
        evaluationCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reactivatePaper"
  ): TypedContractMethod<[paperId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reviewerEvaluations"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitEvaluation"
  ): TypedContractMethod<
    [
      paperId: BigNumberish,
      _recommendation: boolean,
      _originality: BigNumberish,
      _quality: BigNumberish,
      _clarity: BigNumberish,
      _significance: BigNumberish,
      comments: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitPaper"
  ): TypedContractMethod<
    [title: string, authors: string, ipfsHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "EvaluationRevealed"
  ): TypedContractEvent<
    EvaluationRevealedEvent.InputTuple,
    EvaluationRevealedEvent.OutputTuple,
    EvaluationRevealedEvent.OutputObject
  >;
  getEvent(
    key: "EvaluationSubmitted"
  ): TypedContractEvent<
    EvaluationSubmittedEvent.InputTuple,
    EvaluationSubmittedEvent.OutputTuple,
    EvaluationSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaperSubmitted"
  ): TypedContractEvent<
    PaperSubmittedEvent.InputTuple,
    PaperSubmittedEvent.OutputTuple,
    PaperSubmittedEvent.OutputObject
  >;

  filters: {
    "EvaluationRevealed(uint256,uint256,bool,uint8)": TypedContractEvent<
      EvaluationRevealedEvent.InputTuple,
      EvaluationRevealedEvent.OutputTuple,
      EvaluationRevealedEvent.OutputObject
    >;
    EvaluationRevealed: TypedContractEvent<
      EvaluationRevealedEvent.InputTuple,
      EvaluationRevealedEvent.OutputTuple,
      EvaluationRevealedEvent.OutputObject
    >;

    "EvaluationSubmitted(uint256,uint256,address,uint256)": TypedContractEvent<
      EvaluationSubmittedEvent.InputTuple,
      EvaluationSubmittedEvent.OutputTuple,
      EvaluationSubmittedEvent.OutputObject
    >;
    EvaluationSubmitted: TypedContractEvent<
      EvaluationSubmittedEvent.InputTuple,
      EvaluationSubmittedEvent.OutputTuple,
      EvaluationSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaperSubmitted(uint256,string,address,uint256)": TypedContractEvent<
      PaperSubmittedEvent.InputTuple,
      PaperSubmittedEvent.OutputTuple,
      PaperSubmittedEvent.OutputObject
    >;
    PaperSubmitted: TypedContractEvent<
      PaperSubmittedEvent.InputTuple,
      PaperSubmittedEvent.OutputTuple,
      PaperSubmittedEvent.OutputObject
    >;
  };
}
