/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AcademicReview {
  export type ReviewStruct = {
    paperId: BigNumberish;
    reviewer: AddressLike;
    encryptedRecommendation: BytesLike;
    encryptedQuality: BytesLike;
    comments: string;
    timestamp: BigNumberish;
  };

  export type ReviewStructOutput = [
    paperId: bigint,
    reviewer: string,
    encryptedRecommendation: string,
    encryptedQuality: string,
    comments: string,
    timestamp: bigint
  ] & {
    paperId: bigint;
    reviewer: string;
    encryptedRecommendation: string;
    encryptedQuality: string;
    comments: string;
    timestamp: bigint;
  };

  export type PaperStruct = {
    id: BigNumberish;
    title: string;
    paperAbstract: string;
    category: string;
    author: AddressLike;
    timestamp: BigNumberish;
    reviewCount: BigNumberish;
    isActive: boolean;
  };

  export type PaperStructOutput = [
    id: bigint,
    title: string,
    paperAbstract: string,
    category: string,
    author: string,
    timestamp: bigint,
    reviewCount: bigint,
    isActive: boolean
  ] & {
    id: bigint;
    title: string;
    paperAbstract: string;
    category: string;
    author: string;
    timestamp: bigint;
    reviewCount: bigint;
    isActive: boolean;
  };
}

export interface AcademicReviewInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "deactivatePaper"
      | "getEncryptedReview"
      | "getPaperReviews"
      | "getPapersForReview"
      | "getTotalCounts"
      | "getUserPapers"
      | "hasReviewed"
      | "owner"
      | "paperCounter"
      | "paperReviews"
      | "papers"
      | "renounceOwnership"
      | "reviewCounter"
      | "reviews"
      | "submitPaper"
      | "submitReview"
      | "togglePaperStatus"
      | "transferOwnership"
      | "userPapers"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PaperSubmitted"
      | "ReviewDecrypted"
      | "ReviewSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivatePaper",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedReview",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPaperReviews",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPapersForReview",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalCounts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserPapers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasReviewed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paperCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "paperReviews",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "papers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reviewCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reviews",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitPaper",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReview",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "togglePaperStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userPapers",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivatePaper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaperReviews",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPapersForReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserPapers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReviewed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paperCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paperReviews",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "papers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reviewCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reviews", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitPaper",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitReview",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "togglePaperStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userPapers", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaperSubmittedEvent {
  export type InputTuple = [
    paperId: BigNumberish,
    author: AddressLike,
    title: string,
    category: string
  ];
  export type OutputTuple = [
    paperId: bigint,
    author: string,
    title: string,
    category: string
  ];
  export interface OutputObject {
    paperId: bigint;
    author: string;
    title: string;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewDecryptedEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    recommendation: boolean,
    quality: BigNumberish
  ];
  export type OutputTuple = [
    reviewId: bigint,
    recommendation: boolean,
    quality: bigint
  ];
  export interface OutputObject {
    reviewId: bigint;
    recommendation: boolean;
    quality: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewSubmittedEvent {
  export type InputTuple = [
    reviewId: BigNumberish,
    paperId: BigNumberish,
    reviewer: AddressLike
  ];
  export type OutputTuple = [
    reviewId: bigint,
    paperId: bigint,
    reviewer: string
  ];
  export interface OutputObject {
    reviewId: bigint;
    paperId: bigint;
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AcademicReview extends BaseContract {
  connect(runner?: ContractRunner | null): AcademicReview;
  waitForDeployment(): Promise<this>;

  interface: AcademicReviewInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  deactivatePaper: TypedContractMethod<
    [_paperId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEncryptedReview: TypedContractMethod<
    [_reviewId: BigNumberish],
    [
      [string, string] & {
        encryptedRecommendation: string;
        encryptedQuality: string;
      }
    ],
    "view"
  >;

  getPaperReviews: TypedContractMethod<
    [_paperId: BigNumberish],
    [AcademicReview.ReviewStructOutput[]],
    "view"
  >;

  getPapersForReview: TypedContractMethod<
    [],
    [AcademicReview.PaperStructOutput[]],
    "view"
  >;

  getTotalCounts: TypedContractMethod<
    [],
    [[bigint, bigint] & { totalPapers: bigint; totalReviews: bigint }],
    "view"
  >;

  getUserPapers: TypedContractMethod<
    [],
    [AcademicReview.PaperStructOutput[]],
    "view"
  >;

  hasReviewed: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  paperCounter: TypedContractMethod<[], [bigint], "view">;

  paperReviews: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  papers: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        title: string;
        paperAbstract: string;
        category: string;
        author: string;
        timestamp: bigint;
        reviewCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reviewCounter: TypedContractMethod<[], [bigint], "view">;

  reviews: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint] & {
        paperId: bigint;
        reviewer: string;
        encryptedRecommendation: string;
        encryptedQuality: string;
        comments: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  submitPaper: TypedContractMethod<
    [_title: string, _paperAbstract: string, _category: string],
    [void],
    "nonpayable"
  >;

  submitReview: TypedContractMethod<
    [
      _paperId: BigNumberish,
      _encryptedRecommendation: BytesLike,
      _recommendationProof: BytesLike,
      _encryptedQuality: BytesLike,
      _qualityProof: BytesLike,
      _comments: string
    ],
    [void],
    "nonpayable"
  >;

  togglePaperStatus: TypedContractMethod<
    [_paperId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userPapers: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivatePaper"
  ): TypedContractMethod<[_paperId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEncryptedReview"
  ): TypedContractMethod<
    [_reviewId: BigNumberish],
    [
      [string, string] & {
        encryptedRecommendation: string;
        encryptedQuality: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPaperReviews"
  ): TypedContractMethod<
    [_paperId: BigNumberish],
    [AcademicReview.ReviewStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPapersForReview"
  ): TypedContractMethod<[], [AcademicReview.PaperStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getTotalCounts"
  ): TypedContractMethod<
    [],
    [[bigint, bigint] & { totalPapers: bigint; totalReviews: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserPapers"
  ): TypedContractMethod<[], [AcademicReview.PaperStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "hasReviewed"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paperCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "paperReviews"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "papers"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint, bigint, boolean] & {
        id: bigint;
        title: string;
        paperAbstract: string;
        category: string;
        author: string;
        timestamp: bigint;
        reviewCount: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reviewCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reviews"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, string, bigint] & {
        paperId: bigint;
        reviewer: string;
        encryptedRecommendation: string;
        encryptedQuality: string;
        comments: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitPaper"
  ): TypedContractMethod<
    [_title: string, _paperAbstract: string, _category: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitReview"
  ): TypedContractMethod<
    [
      _paperId: BigNumberish,
      _encryptedRecommendation: BytesLike,
      _recommendationProof: BytesLike,
      _encryptedQuality: BytesLike,
      _qualityProof: BytesLike,
      _comments: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "togglePaperStatus"
  ): TypedContractMethod<[_paperId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userPapers"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaperSubmitted"
  ): TypedContractEvent<
    PaperSubmittedEvent.InputTuple,
    PaperSubmittedEvent.OutputTuple,
    PaperSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewDecrypted"
  ): TypedContractEvent<
    ReviewDecryptedEvent.InputTuple,
    ReviewDecryptedEvent.OutputTuple,
    ReviewDecryptedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewSubmitted"
  ): TypedContractEvent<
    ReviewSubmittedEvent.InputTuple,
    ReviewSubmittedEvent.OutputTuple,
    ReviewSubmittedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaperSubmitted(uint256,address,string,string)": TypedContractEvent<
      PaperSubmittedEvent.InputTuple,
      PaperSubmittedEvent.OutputTuple,
      PaperSubmittedEvent.OutputObject
    >;
    PaperSubmitted: TypedContractEvent<
      PaperSubmittedEvent.InputTuple,
      PaperSubmittedEvent.OutputTuple,
      PaperSubmittedEvent.OutputObject
    >;

    "ReviewDecrypted(uint256,bool,uint8)": TypedContractEvent<
      ReviewDecryptedEvent.InputTuple,
      ReviewDecryptedEvent.OutputTuple,
      ReviewDecryptedEvent.OutputObject
    >;
    ReviewDecrypted: TypedContractEvent<
      ReviewDecryptedEvent.InputTuple,
      ReviewDecryptedEvent.OutputTuple,
      ReviewDecryptedEvent.OutputObject
    >;

    "ReviewSubmitted(uint256,uint256,address)": TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;
    ReviewSubmitted: TypedContractEvent<
      ReviewSubmittedEvent.InputTuple,
      ReviewSubmittedEvent.OutputTuple,
      ReviewSubmittedEvent.OutputObject
    >;
  };
}
