/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as zamaLinkCampaignSol from "./ZamaLinkCampaign.sol";
export type { zamaLinkCampaignSol };
export type { AcademicEvaluation } from "./AcademicEvaluation";
export type { AcademicReview } from "./AcademicReview";
export type { ZLETHWrapper } from "./ZLETHWrapper";
