/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ZLETHWrapperInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowDecryption"
      | "balanceOf"
      | "confidentialProtocolId"
      | "confidentialTransfer(address,bytes32,bytes)"
      | "confidentialTransfer(address,bytes32)"
      | "contractHealth"
      | "decimals"
      | "deposit"
      | "emergencyWithdrawETH"
      | "finalizeWithdraw"
      | "name"
      | "rate"
      | "symbol"
      | "totalEthLocked"
      | "withdraw(address,address,bytes32,bytes)"
      | "withdraw(address,address,bytes32)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ETHUnwrapped" | "ETHWrapped" | "UnwrapRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowDecryption",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransfer(address,bytes32,bytes)",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransfer(address,bytes32)",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractHealth",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeWithdraw",
    values: [BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "rate", values?: undefined): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalEthLocked",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw(address,address,bytes32,bytes)",
    values: [AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw(address,address,bytes32)",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "allowDecryption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransfer(address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransfer(address,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractHealth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawETH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalEthLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdraw(address,address,bytes32,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdraw(address,address,bytes32)",
    data: BytesLike
  ): Result;
}

export namespace ETHUnwrappedEvent {
  export type InputTuple = [user: AddressLike, ethAmount: BigNumberish];
  export type OutputTuple = [user: string, ethAmount: bigint];
  export interface OutputObject {
    user: string;
    ethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ETHWrappedEvent {
  export type InputTuple = [
    user: AddressLike,
    ethAmount: BigNumberish,
    zlethAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    ethAmount: bigint,
    zlethAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    ethAmount: bigint;
    zlethAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnwrapRequestedEvent {
  export type InputTuple = [user: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [user: string, requestId: bigint];
  export interface OutputObject {
    user: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZLETHWrapper extends BaseContract {
  connect(runner?: ContractRunner | null): ZLETHWrapper;
  waitForDeployment(): Promise<this>;

  interface: ZLETHWrapperInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowDecryption: TypedContractMethod<
    [spender: AddressLike],
    [void],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  "confidentialTransfer(address,bytes32,bytes)": TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  "confidentialTransfer(address,bytes32)": TypedContractMethod<
    [to: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;

  contractHealth: TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean] & {
        ethBalance: bigint;
        ethLocked: bigint;
        isHealthy: boolean;
      }
    ],
    "view"
  >;

  decimals: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[to: AddressLike], [void], "payable">;

  emergencyWithdrawETH: TypedContractMethod<[], [void], "nonpayable">;

  finalizeWithdraw: TypedContractMethod<
    [
      requestID: BigNumberish,
      zlethAmount: BigNumberish,
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  rate: TypedContractMethod<[], [bigint], "view">;

  symbol: TypedContractMethod<[], [string], "view">;

  totalEthLocked: TypedContractMethod<[], [bigint], "view">;

  "withdraw(address,address,bytes32,bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  "withdraw(address,address,bytes32)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowDecryption"
  ): TypedContractMethod<[spender: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialTransfer(address,bytes32,bytes)"
  ): TypedContractMethod<
    [to: AddressLike, encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransfer(address,bytes32)"
  ): TypedContractMethod<
    [to: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contractHealth"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean] & {
        ethBalance: bigint;
        ethLocked: bigint;
        isHealthy: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[to: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawETH"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeWithdraw"
  ): TypedContractMethod<
    [
      requestID: BigNumberish,
      zlethAmount: BigNumberish,
      signatures: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalEthLocked"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw(address,address,bytes32,bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw(address,address,bytes32)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ETHUnwrapped"
  ): TypedContractEvent<
    ETHUnwrappedEvent.InputTuple,
    ETHUnwrappedEvent.OutputTuple,
    ETHUnwrappedEvent.OutputObject
  >;
  getEvent(
    key: "ETHWrapped"
  ): TypedContractEvent<
    ETHWrappedEvent.InputTuple,
    ETHWrappedEvent.OutputTuple,
    ETHWrappedEvent.OutputObject
  >;
  getEvent(
    key: "UnwrapRequested"
  ): TypedContractEvent<
    UnwrapRequestedEvent.InputTuple,
    UnwrapRequestedEvent.OutputTuple,
    UnwrapRequestedEvent.OutputObject
  >;

  filters: {
    "ETHUnwrapped(address,uint256)": TypedContractEvent<
      ETHUnwrappedEvent.InputTuple,
      ETHUnwrappedEvent.OutputTuple,
      ETHUnwrappedEvent.OutputObject
    >;
    ETHUnwrapped: TypedContractEvent<
      ETHUnwrappedEvent.InputTuple,
      ETHUnwrappedEvent.OutputTuple,
      ETHUnwrappedEvent.OutputObject
    >;

    "ETHWrapped(address,uint256,uint64)": TypedContractEvent<
      ETHWrappedEvent.InputTuple,
      ETHWrappedEvent.OutputTuple,
      ETHWrappedEvent.OutputObject
    >;
    ETHWrapped: TypedContractEvent<
      ETHWrappedEvent.InputTuple,
      ETHWrappedEvent.OutputTuple,
      ETHWrappedEvent.OutputObject
    >;

    "UnwrapRequested(address,uint256)": TypedContractEvent<
      UnwrapRequestedEvent.InputTuple,
      UnwrapRequestedEvent.OutputTuple,
      UnwrapRequestedEvent.OutputObject
    >;
    UnwrapRequested: TypedContractEvent<
      UnwrapRequestedEvent.InputTuple,
      UnwrapRequestedEvent.OutputTuple,
      UnwrapRequestedEvent.OutputObject
    >;
  };
}
